language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - laravel=^5.5 scout=^7.0
    - laravel=^6.0 scout=^7.0
    - laravel=^6.0 scout=^8.0
    - laravel=^7.0 scout=^8.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer require "illuminate/bus:${laravel}" --no-update
  - travis_retry composer require "illuminate/contracts:${laravel}" --no-update
  - travis_retry composer require "illuminate/database:${laravel}" --no-update
  - travis_retry composer require "illuminate/pagination:${laravel}" --no-update
  - travis_retry composer require "illuminate/queue:${laravel}" --no-update
  - travis_retry composer require "illuminate/support:${laravel}" --no-update
  - travis_retry composer require "laravel/scout:${scout}" --no-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --verbose
